<?php

/**
 * Spambot CiviCRM - hook into user_delete, so that the corresponding Civi contact is
 * deleted whenever spambot deletes a user
 * andyw@circle, 27/03/2014
 */

/**
 * Implementation of hook_user_delete
 */
function spambot_civicrm_user_delete($account) {
    
    # see if spambot_cron exists in the call stack - we only want to delete the
    # Civi contact if it's spambot that is deleting the user
    $via_spambot = false;
    foreach (debug_backtrace() as $backtrace_item) {
        if (isset($backtrace_item['function']) and $backtrace_item['function'] == 'spambot_cron') {
            $via_spambot = true;
            break;
        }
    }

    if ($via_spambot) {

        civicrm_initialize();
        
        # attempt to find associated contact id for the user
        $result = civicrm_api('ufmatch', 'getsingle', array(
            'version' => 3,
            'uf_id'   => $account->uid
        ));

        # no match ..
        if (!$result['count'])
            return watchdog(
                'spambot_civicrm', 
                t('Could not find matching contact record for uid @uid when deleting user via spambot', array(
                    '@uid' => $account->uid
                )),
                array(),
                WATCHDOG_ERROR
            );           

        # some other kind of error ..
        if ($result['is_error'])
            return watchdog(
                'spambot_civicrm', 
                t('An error occurred finding UFMatch for uid @uid: @message', array(
                    '@uid'     => $account->uid,
                    '@message' => $result['error_message']
                )),
                array(),
                WATCHDOG_ERROR
            );

        # delete contact record
        $delete_result = civicrm_api('contact', 'delete', array(
            'version'       => 3,
            'id'            => $result['contact_id'],
            'skip_undelete' => 1
        ));

        # check for errors
        if ($delete_result['is_error'])
            return watchdog(
                'spambot_civicrm', 
                t('An error occurred deleting contact record for contact id @contact_id: @message', array(
                    '@contact_id' => $result['contact_id'],
                    '@message'    => $delete_result['error_message']
                )),
                array(),
                WATCHDOG_ERROR
            );

        # note: does that delete the ufmatch record? probably, but better check


    }

}